### ISSUE TITLE
Failing to find font packages

### ISSUE THREAD

**Issue by Rhys-McAlister** [cmarquardt/quarto-simple-article#2]
Hi, I've been having an issue where when I tried to render the template I keep getting errors around not having the necessary fonts 
TexGyrePagella or lucidabrightOT. I'm having this same issue on two separate computers and I've attached the log file below. I apologise if this is a simple issue, I'm not very familiar with latex.

[lr222.log](https://github.com/cmarquardt/quarto-simple-article/files/9876797/lr222.log)

**Comment by cmarquardt** [comment]
Hello,

the Lucida fonts (lucidabrightOT) are, unfortunately, not freely available - unless you haven't bought them from, e.g., the [TeX User Group website](https://tug.org/store/lucida/index.html) and installed them, your LaTeX installation won't have them.

However, TeX Gyre Pagella (which is a free font similar to Palatino) should be available with TeXLive. From your logs, I see you are using TinyTeX; maybe the fonts need to be downloaded manually. From this (unrelated) [answer on StackExchange](https://tex.stackexchange.com/a/478280) I take that

    > tlmgr install tex-gyre

should do that - could you give that a try?

You could also try to use `pdflatex` as your LaTeX engine; that would use LaTeX's `mathpazo` package for mathematics and your system's Palatino fonts as I remember, but you might run into trouble if TinyTeX hasn't that package installed.

There is some information on how to [maintain tinyTeX manually](https://yihui.org/tinytex/#maintenance), including how to add packages and update it. I understand that for RMarkdown documents, missing packages should be downloaded and installed automatically. Maybe that doesn't work yet for Quarto documents; or maybe it doesn't recognise the need to download additional fonts.

Unfortunately, I have very little experience with TinyTeX myself; so I don't know if I can help much beyond the above. But let me know if the above command doesn't work, and we'll find out what to do.

**Comment by Pierre9344** [comment]
Hello,

I have the same issue. I tried to remove the lucida option:
```
format:
  simple-article-pdf:
    keep-tex: true
    indent: false
    classoption: 
     - 9pt
     - twocolumn
     - twoside
```

I got an error telling that the TeXGyrePagellaMath font is not found but I already have the tex-gyre package installed.

**Comment by cmarquardt** [comment]
Hmm. Could you run

    tlmgr info tex-gyre-math

to see if the corresponding math fonts are installed? If not, does 

    tlmgr install tex-gyre-math

help?

I would think that font problems are not related to Quarto, but rather to your TeX installation. To simplify the testing, save the following in a file called `test.tex`:

```
\documentclass{article}

\usepackage{fontspec}
\setromanfont[Ligatures=TeX]{TeX Gyre Pagella}
\usepackage[math-style=ISO,bold-style=ISO]{unicode-math}
\setmathfont{TeX Gyre Pagella Math}

\begin{document}

$$ \int_{0}^{\infty} e^{-\frac{1}{2} \xi^{2}} d \xi $$

\end{document}
```

and then run

    lualatex test.tex

If that works, it should also work from Quarto. If not, could you say which TeX installation you use and on which OS?

**Comment by cmarquardt** [comment]
Hmm - as there is no response, I'll close this.

**Comment by MohammedAliSharafuddin** [comment]
I tried to use this package and ended up with the same font issue (tex-gyre-math). Spent few hours trying to figure out the issue. But cant solve it. 
How can I change the math font to "Latin Modern Math" or any other font that is default in Ubuntu. And how can I change all the other text fonts to "Times new roman"?
Thanks for the help in advance.

**Comment by jonathanmbinder** [comment]
> I tried to use this package and ended up with the same font issue (tex-gyre-math). Spent few hours trying to figure out the issue. But cant solve it. How can I change the math font to "Latin Modern Math" or any other font that is default in Ubuntu. And how can I change all the other text fonts to "Times new roman"? Thanks for the help in advance.

I'm also trying to change the font without success. Can you please advise? Thank you.
